### ISSUE TITLE
[Bug + Docs] add note, that cli tool is only usable in the Linkfree repo / folder + Final prompt message

### ISSUE THREAD

**Issue by schmelto** [Pradumnasaraf/LinkFree-CLI#1]
### Description

it should be clear that the CLI shlould only be ran in a forked linkfree folder.
Further the `wohooo`-messages imo is displayed to early and not shown if such an error is thrown. (https://github.com/Pradumnasaraf/LinkFree-CLI/blob/main/src/index.js#L45)

### Screenshots

![image](https://user-images.githubusercontent.com/30869493/186849275-b6f88fa5-bcee-4ef9-9b88-760aee0a223d.png)

**Comment by Pradumnasaraf** [comment]
Hey! tom, 
Thanks for reporting, this is something new. I didn't get why you get that error, because even if you or the main repo (not forked) it will create a file. Hope you are at the root of the linkfree folder. 
Can you give me more context

**Comment by Pradumnasaraf** [comment]
> I've tried it outside of the linkfree repo / also if it would not work in the nextjs branch. The error was after installing it in an empty repository and running the cli there

Got your point. instead of a `woohoo` message, it should prompt that you are in the root dir of linkfree, Indeed?

**Comment by Pradumnasaraf** [comment]
Hey @schmelto 

Released the `v1.1.2` with the changes. Can do install the latest changes and give your feedback?

 **Again, thank you so much for reporting it**. Also, here is the demo video after the changes.

https://user-images.githubusercontent.com/51878265/186906101-d356ed49-f504-4bea-ae2a-67f11c095ec9.mp4

### (Not closing the issue because the docs part is remaining)
